<?php

namespace Tests\Feature;

use App\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Laravel\Sanctum\Sanctum;
use Tests\TestCase;

class SalesRecordTest extends TestCase
{
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        Sanctum::actingAs(
            factory(User::class)->create()
        );
    }

    public function test_index()
    {
        $response = $this->getJson('/api/sales/records');

        $response->assertSuccessful();
        $response->assertHeader('content-type', 'application/json');
    }

    public function test_store(){
        $data = [
            'product_id' => '4',
            'product' => 'Coca Cola',
            'category' => 'Bebidas',
            'price' => '$20.00',
            'amount' => '2',
            'total_price' => '$40.00'
        ];

        $response = $this->postJson('/api/sales/records', $data);

        $response->assertSuccessful();
        $response->assertHeader('content-type', 'application/json');
    }
}
